export type DataType = {
  id: number
  avatar: string
  fullName: string
  post: string
  email: string
  city: string
  start_date: string
  salary: number
  age: number
  experience: string
  status: number
}

const data: any[] = [
  {
    'INV #': 'INV001',
    'Completed By': 'John Doe',
    'Client Name': 'ABC Corp',
    'Date Sent': '2024-04-01',
    Carrier: 'XYZ Shipping',
    OA: 'OA123',
    Umpire: 'Jane Smith',
    Address: '123 Main St, Anytown, USA',
    'Supplement Amt': 100.0,
    Percentage: 10,
    'Date Approved': '2024-04-15',
    Turnaround: 7,
    'Comm Amt': 50.0,
    Notes: 'Additional inspection required',
    'Date QB Invoiced': '2024-04-20',
    'Amt TS Paid': 150.0
  },
  {
    'INV #': 'INV002',
    'Completed By': 'Alice Johnson',
    'Client Name': 'DEF Inc',
    'Date Sent': '2024-04-05',
    Carrier: 'ABC Logistics',
    OA: 'OA456',
    Umpire: 'Bob Williams',
    Address: '456 Oak St, Sometown, USA',
    'Supplement Amt': 50.0,
    Percentage: 8,
    'Date Approved': '2024-04-18',
    Turnaround: 5,
    'Comm Amt': 30.0,
    Notes: 'No issues found',
    'Date QB Invoiced': '2024-04-22',
    'Amt TS Paid': 80.0
  },
  {
    'INV #': 'INV003',
    'Completed By': 'Emily Brown',
    'Client Name': 'GHI Ltd',
    'Date Sent': '2024-04-10',
    Carrier: 'LMN Freight',
    OA: 'OA789',
    Umpire: 'Michael Jones',
    Address: '789 Pine St, Othertown, USA',
    'Supplement Amt': 75.0,
    Percentage: 12,
    'Date Approved': '2024-04-25',
    Turnaround: 8,
    'Comm Amt': 40.0,
    Notes: 'Customer requested expedited service',
    'Date QB Invoiced': '2024-04-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV004',
    'Completed By': 'David Lee',
    'Client Name': 'JKL Co',
    'Date Sent': '2024-04-15',
    Carrier: 'OPQ Express',
    OA: 'OA012',
    Umpire: 'Sarah Garcia',
    Address: '012 Maple St, Anothertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 15,
    'Date Approved': '2024-05-02',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Damage discovered during inspection',
    'Date QB Invoiced': '2024-05-05',
    'Amt TS Paid': 180.0
  },
  {
    'INV #': 'INV005',
    'Completed By': 'Chris Taylor',
    'Client Name': 'MNO Corporation',
    'Date Sent': '2024-04-20',
    Carrier: 'RST Transport',
    OA: 'OA345',
    Umpire: 'Linda Martinez',
    Address: '345 Elm St, Lasttown, USA',
    'Supplement Amt': 90.0,
    Percentage: 9,
    'Date Approved': '2024-05-05',
    Turnaround: 7,
    'Comm Amt': 45.0,
    Notes: 'Client satisfied with service',
    'Date QB Invoiced': '2024-05-08',
    'Amt TS Paid': 135.0
  },
  {
    'INV #': 'INV006',
    'Completed By': 'Emma Wilson',
    'Client Name': 'PQR Ltd',
    'Date Sent': '2024-04-25',
    Carrier: 'UVW Shipping',
    OA: 'OA678',
    Umpire: 'Kevin Brown',
    Address: '678 Cedar St, Newtown, USA',
    'Supplement Amt': 60.0,
    Percentage: 11,
    'Date Approved': '2024-05-10',
    Turnaround: 5,
    'Comm Amt': 35.0,
    Notes: 'Minor damages reported',
    'Date QB Invoiced': '2024-05-12',
    'Amt TS Paid': 95.0
  },
  {
    'INV #': 'INV007',
    'Completed By': 'Olivia Clark',
    'Client Name': 'STU Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'WXY Logistics',
    OA: 'OA901',
    Umpire: 'Jason Wilson',
    Address: '901 Walnut St, Finaltown, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-05-15',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'High-quality service provided',
    'Date QB Invoiced': '2024-05-18',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV008',
    'Completed By': 'Sophia Rodriguez',
    'Client Name': 'VWX Corp',
    'Date Sent': '2024-05-05',
    Carrier: 'YZA Express',
    OA: 'OA234',
    Umpire: 'William Taylor',
    Address: '234 Pine St, Summitville, USA',
    'Supplement Amt': 100.0,
    Percentage: 12,
    'Date Approved': '2024-05-20',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 155.0
  },
  {
    'INV #': 'INV009',
    'Completed By': 'Noah Baker',
    'Client Name': 'XYZ Corporation',
    'Date Sent': '2024-05-10',
    Carrier: 'BCD Freight',
    OA: 'OA567',
    Umpire: 'Jessica Wright',
    Address: '567 Oak St, Mountaintown, USA',
    'Supplement Amt': 70.0,
    Percentage: 9,
    'Date Approved': '2024-05-25',
    Turnaround: 6,
    'Comm Amt': 45.0,
    Notes: 'Client requested detailed report',
    'Date QB Invoiced': '2024-05-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV010',
    'Completed By': 'James Wright',
    'Client Name': 'EFG Inc',
    'Date Sent': '2024-05-15',
    Carrier: 'CDE Logistics',
    OA: 'OA890',
    Umpire: 'Sophie Harris',
    Address: '890 Cedar St, Hilltown, USA',
    'Supplement Amt': 110.0,
    Percentage: 13,
    'Date Approved': '2024-06-01',
    Turnaround: 7,
    'Comm Amt': 60.0,
    Notes: 'Unforeseen damages found',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 170.0
  },
  {
    'INV #': 'INV011',
    'Completed By': 'Ava Moore',
    'Client Name': 'HIJ Enterprises',
    'Date Sent': '2024-05-20',
    Carrier: 'FGH Transport',
    OA: 'OA345',
    Umpire: 'Daniel Jackson',
    Address: '345 Maple St, Valleysville, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-05',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Quick resolution of issues',
    'Date QB Invoiced': '2024-06-08',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV012',
    'Completed By': 'Harper Young',
    'Client Name': 'LMN Corporation',
    'Date Sent': '2024-05-25',
    Carrier: 'IJK Express',
    OA: 'OA678',
    Umpire: 'Matthew Clark',
    Address: '678 Elm St, Glentown, USA',
    'Supplement Amt': 90.0,
    Percentage: 12,
    'Date Approved': '2024-06-10',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Detailed report provided to client',
    'Date QB Invoiced': '2024-06-12',
    'Amt TS Paid': 145.0
  },
  {
    'INV #': 'INV013',
    'Completed By': 'Evelyn Turner',
    'Client Name': 'OPQ Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'LMN Shipping',
    OA: 'OA901',
    Umpire: 'Ethan Roberts',
    Address: '901 Oak St, Hometown, USA',
    'Supplement Amt': 100.0,
    Percentage: 11,
    'Date Approved': '2024-05-20',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Client satisfaction survey completed',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 160.0
  },
  {
    'INV #': 'INV014',
    'Completed By': 'Logan King',
    'Client Name': 'RST Ltd',
    'Date Sent': '2024-05-10',
    Carrier: 'UVW Freight',
    OA: 'OA234',
    Umpire: 'Aria Rivera',
    Address: '234 Cedar St, Rivertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 13,
    'Date Approved': '2024-05-28',
    Turnaround: 7,
    'Comm Amt': 70.0,
    Notes: 'Exceptional service provided',
    'Date QB Invoiced': '2024-05-30',
    'Amt TS Paid': 190.0
  },
  {
    'INV #': 'INV015',
    'Completed By': 'Mia Scott',
    'Client Name': 'WXY Corporation',
    'Date Sent': '2024-05-15',
    Carrier: 'YZA Transport',
    OA: 'OA567',
    Umpire: 'Lucas Gray',
    Address: '567 Walnut St, Newland, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-02',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV001',
    'Completed By': 'John Doe',
    'Client Name': 'ABC Corp',
    'Date Sent': '2024-04-01',
    Carrier: 'XYZ Shipping',
    OA: 'OA123',
    Umpire: 'Jane Smith',
    Address: '123 Main St, Anytown, USA',
    'Supplement Amt': 100.0,
    Percentage: 10,
    'Date Approved': '2024-04-15',
    Turnaround: 7,
    'Comm Amt': 50.0,
    Notes: 'Additional inspection required',
    'Date QB Invoiced': '2024-04-20',
    'Amt TS Paid': 150.0
  },
  {
    'INV #': 'INV002',
    'Completed By': 'Alice Johnson',
    'Client Name': 'DEF Inc',
    'Date Sent': '2024-04-05',
    Carrier: 'ABC Logistics',
    OA: 'OA456',
    Umpire: 'Bob Williams',
    Address: '456 Oak St, Sometown, USA',
    'Supplement Amt': 50.0,
    Percentage: 8,
    'Date Approved': '2024-04-18',
    Turnaround: 5,
    'Comm Amt': 30.0,
    Notes: 'No issues found',
    'Date QB Invoiced': '2024-04-22',
    'Amt TS Paid': 80.0
  },
  {
    'INV #': 'INV003',
    'Completed By': 'Emily Brown',
    'Client Name': 'GHI Ltd',
    'Date Sent': '2024-04-10',
    Carrier: 'LMN Freight',
    OA: 'OA789',
    Umpire: 'Michael Jones',
    Address: '789 Pine St, Othertown, USA',
    'Supplement Amt': 75.0,
    Percentage: 12,
    'Date Approved': '2024-04-25',
    Turnaround: 8,
    'Comm Amt': 40.0,
    Notes: 'Customer requested expedited service',
    'Date QB Invoiced': '2024-04-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV004',
    'Completed By': 'David Lee',
    'Client Name': 'JKL Co',
    'Date Sent': '2024-04-15',
    Carrier: 'OPQ Express',
    OA: 'OA012',
    Umpire: 'Sarah Garcia',
    Address: '012 Maple St, Anothertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 15,
    'Date Approved': '2024-05-02',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Damage discovered during inspection',
    'Date QB Invoiced': '2024-05-05',
    'Amt TS Paid': 180.0
  },
  {
    'INV #': 'INV005',
    'Completed By': 'Chris Taylor',
    'Client Name': 'MNO Corporation',
    'Date Sent': '2024-04-20',
    Carrier: 'RST Transport',
    OA: 'OA345',
    Umpire: 'Linda Martinez',
    Address: '345 Elm St, Lasttown, USA',
    'Supplement Amt': 90.0,
    Percentage: 9,
    'Date Approved': '2024-05-05',
    Turnaround: 7,
    'Comm Amt': 45.0,
    Notes: 'Client satisfied with service',
    'Date QB Invoiced': '2024-05-08',
    'Amt TS Paid': 135.0
  },
  {
    'INV #': 'INV006',
    'Completed By': 'Emma Wilson',
    'Client Name': 'PQR Ltd',
    'Date Sent': '2024-04-25',
    Carrier: 'UVW Shipping',
    OA: 'OA678',
    Umpire: 'Kevin Brown',
    Address: '678 Cedar St, Newtown, USA',
    'Supplement Amt': 60.0,
    Percentage: 11,
    'Date Approved': '2024-05-10',
    Turnaround: 5,
    'Comm Amt': 35.0,
    Notes: 'Minor damages reported',
    'Date QB Invoiced': '2024-05-12',
    'Amt TS Paid': 95.0
  },
  {
    'INV #': 'INV007',
    'Completed By': 'Olivia Clark',
    'Client Name': 'STU Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'WXY Logistics',
    OA: 'OA901',
    Umpire: 'Jason Wilson',
    Address: '901 Walnut St, Finaltown, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-05-15',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'High-quality service provided',
    'Date QB Invoiced': '2024-05-18',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV008',
    'Completed By': 'Sophia Rodriguez',
    'Client Name': 'VWX Corp',
    'Date Sent': '2024-05-05',
    Carrier: 'YZA Express',
    OA: 'OA234',
    Umpire: 'William Taylor',
    Address: '234 Pine St, Summitville, USA',
    'Supplement Amt': 100.0,
    Percentage: 12,
    'Date Approved': '2024-05-20',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 155.0
  },
  {
    'INV #': 'INV009',
    'Completed By': 'Noah Baker',
    'Client Name': 'XYZ Corporation',
    'Date Sent': '2024-05-10',
    Carrier: 'BCD Freight',
    OA: 'OA567',
    Umpire: 'Jessica Wright',
    Address: '567 Oak St, Mountaintown, USA',
    'Supplement Amt': 70.0,
    Percentage: 9,
    'Date Approved': '2024-05-25',
    Turnaround: 6,
    'Comm Amt': 45.0,
    Notes: 'Client requested detailed report',
    'Date QB Invoiced': '2024-05-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV010',
    'Completed By': 'James Wright',
    'Client Name': 'EFG Inc',
    'Date Sent': '2024-05-15',
    Carrier: 'CDE Logistics',
    OA: 'OA890',
    Umpire: 'Sophie Harris',
    Address: '890 Cedar St, Hilltown, USA',
    'Supplement Amt': 110.0,
    Percentage: 13,
    'Date Approved': '2024-06-01',
    Turnaround: 7,
    'Comm Amt': 60.0,
    Notes: 'Unforeseen damages found',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 170.0
  },
  {
    'INV #': 'INV011',
    'Completed By': 'Ava Moore',
    'Client Name': 'HIJ Enterprises',
    'Date Sent': '2024-05-20',
    Carrier: 'FGH Transport',
    OA: 'OA345',
    Umpire: 'Daniel Jackson',
    Address: '345 Maple St, Valleysville, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-05',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Quick resolution of issues',
    'Date QB Invoiced': '2024-06-08',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV012',
    'Completed By': 'Harper Young',
    'Client Name': 'LMN Corporation',
    'Date Sent': '2024-05-25',
    Carrier: 'IJK Express',
    OA: 'OA678',
    Umpire: 'Matthew Clark',
    Address: '678 Elm St, Glentown, USA',
    'Supplement Amt': 90.0,
    Percentage: 12,
    'Date Approved': '2024-06-10',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Detailed report provided to client',
    'Date QB Invoiced': '2024-06-12',
    'Amt TS Paid': 145.0
  },
  {
    'INV #': 'INV013',
    'Completed By': 'Evelyn Turner',
    'Client Name': 'OPQ Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'LMN Shipping',
    OA: 'OA901',
    Umpire: 'Ethan Roberts',
    Address: '901 Oak St, Hometown, USA',
    'Supplement Amt': 100.0,
    Percentage: 11,
    'Date Approved': '2024-05-20',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Client satisfaction survey completed',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 160.0
  },
  {
    'INV #': 'INV014',
    'Completed By': 'Logan King',
    'Client Name': 'RST Ltd',
    'Date Sent': '2024-05-10',
    Carrier: 'UVW Freight',
    OA: 'OA234',
    Umpire: 'Aria Rivera',
    Address: '234 Cedar St, Rivertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 13,
    'Date Approved': '2024-05-28',
    Turnaround: 7,
    'Comm Amt': 70.0,
    Notes: 'Exceptional service provided',
    'Date QB Invoiced': '2024-05-30',
    'Amt TS Paid': 190.0
  },
  {
    'INV #': 'INV015',
    'Completed By': 'Mia Scott',
    'Client Name': 'WXY Corporation',
    'Date Sent': '2024-05-15',
    Carrier: 'YZA Transport',
    OA: 'OA567',
    Umpire: 'Lucas Gray',
    Address: '567 Walnut St, Newland, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-02',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 130.0
  },{
    'INV #': 'INV001',
    'Completed By': 'John Doe',
    'Client Name': 'ABC Corp',
    'Date Sent': '2024-04-01',
    Carrier: 'XYZ Shipping',
    OA: 'OA123',
    Umpire: 'Jane Smith',
    Address: '123 Main St, Anytown, USA',
    'Supplement Amt': 100.0,
    Percentage: 10,
    'Date Approved': '2024-04-15',
    Turnaround: 7,
    'Comm Amt': 50.0,
    Notes: 'Additional inspection required',
    'Date QB Invoiced': '2024-04-20',
    'Amt TS Paid': 150.0
  },
  {
    'INV #': 'INV002',
    'Completed By': 'Alice Johnson',
    'Client Name': 'DEF Inc',
    'Date Sent': '2024-04-05',
    Carrier: 'ABC Logistics',
    OA: 'OA456',
    Umpire: 'Bob Williams',
    Address: '456 Oak St, Sometown, USA',
    'Supplement Amt': 50.0,
    Percentage: 8,
    'Date Approved': '2024-04-18',
    Turnaround: 5,
    'Comm Amt': 30.0,
    Notes: 'No issues found',
    'Date QB Invoiced': '2024-04-22',
    'Amt TS Paid': 80.0
  },
  {
    'INV #': 'INV003',
    'Completed By': 'Emily Brown',
    'Client Name': 'GHI Ltd',
    'Date Sent': '2024-04-10',
    Carrier: 'LMN Freight',
    OA: 'OA789',
    Umpire: 'Michael Jones',
    Address: '789 Pine St, Othertown, USA',
    'Supplement Amt': 75.0,
    Percentage: 12,
    'Date Approved': '2024-04-25',
    Turnaround: 8,
    'Comm Amt': 40.0,
    Notes: 'Customer requested expedited service',
    'Date QB Invoiced': '2024-04-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV004',
    'Completed By': 'David Lee',
    'Client Name': 'JKL Co',
    'Date Sent': '2024-04-15',
    Carrier: 'OPQ Express',
    OA: 'OA012',
    Umpire: 'Sarah Garcia',
    Address: '012 Maple St, Anothertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 15,
    'Date Approved': '2024-05-02',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Damage discovered during inspection',
    'Date QB Invoiced': '2024-05-05',
    'Amt TS Paid': 180.0
  },
  {
    'INV #': 'INV005',
    'Completed By': 'Chris Taylor',
    'Client Name': 'MNO Corporation',
    'Date Sent': '2024-04-20',
    Carrier: 'RST Transport',
    OA: 'OA345',
    Umpire: 'Linda Martinez',
    Address: '345 Elm St, Lasttown, USA',
    'Supplement Amt': 90.0,
    Percentage: 9,
    'Date Approved': '2024-05-05',
    Turnaround: 7,
    'Comm Amt': 45.0,
    Notes: 'Client satisfied with service',
    'Date QB Invoiced': '2024-05-08',
    'Amt TS Paid': 135.0
  },
  {
    'INV #': 'INV006',
    'Completed By': 'Emma Wilson',
    'Client Name': 'PQR Ltd',
    'Date Sent': '2024-04-25',
    Carrier: 'UVW Shipping',
    OA: 'OA678',
    Umpire: 'Kevin Brown',
    Address: '678 Cedar St, Newtown, USA',
    'Supplement Amt': 60.0,
    Percentage: 11,
    'Date Approved': '2024-05-10',
    Turnaround: 5,
    'Comm Amt': 35.0,
    Notes: 'Minor damages reported',
    'Date QB Invoiced': '2024-05-12',
    'Amt TS Paid': 95.0
  },
  {
    'INV #': 'INV007',
    'Completed By': 'Olivia Clark',
    'Client Name': 'STU Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'WXY Logistics',
    OA: 'OA901',
    Umpire: 'Jason Wilson',
    Address: '901 Walnut St, Finaltown, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-05-15',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'High-quality service provided',
    'Date QB Invoiced': '2024-05-18',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV008',
    'Completed By': 'Sophia Rodriguez',
    'Client Name': 'VWX Corp',
    'Date Sent': '2024-05-05',
    Carrier: 'YZA Express',
    OA: 'OA234',
    Umpire: 'William Taylor',
    Address: '234 Pine St, Summitville, USA',
    'Supplement Amt': 100.0,
    Percentage: 12,
    'Date Approved': '2024-05-20',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 155.0
  },
  {
    'INV #': 'INV009',
    'Completed By': 'Noah Baker',
    'Client Name': 'XYZ Corporation',
    'Date Sent': '2024-05-10',
    Carrier: 'BCD Freight',
    OA: 'OA567',
    Umpire: 'Jessica Wright',
    Address: '567 Oak St, Mountaintown, USA',
    'Supplement Amt': 70.0,
    Percentage: 9,
    'Date Approved': '2024-05-25',
    Turnaround: 6,
    'Comm Amt': 45.0,
    Notes: 'Client requested detailed report',
    'Date QB Invoiced': '2024-05-28',
    'Amt TS Paid': 115.0
  },
  {
    'INV #': 'INV010',
    'Completed By': 'James Wright',
    'Client Name': 'EFG Inc',
    'Date Sent': '2024-05-15',
    Carrier: 'CDE Logistics',
    OA: 'OA890',
    Umpire: 'Sophie Harris',
    Address: '890 Cedar St, Hilltown, USA',
    'Supplement Amt': 110.0,
    Percentage: 13,
    'Date Approved': '2024-06-01',
    Turnaround: 7,
    'Comm Amt': 60.0,
    Notes: 'Unforeseen damages found',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 170.0
  },
  {
    'INV #': 'INV011',
    'Completed By': 'Ava Moore',
    'Client Name': 'HIJ Enterprises',
    'Date Sent': '2024-05-20',
    Carrier: 'FGH Transport',
    OA: 'OA345',
    Umpire: 'Daniel Jackson',
    Address: '345 Maple St, Valleysville, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-05',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Quick resolution of issues',
    'Date QB Invoiced': '2024-06-08',
    'Amt TS Paid': 130.0
  },
  {
    'INV #': 'INV012',
    'Completed By': 'Harper Young',
    'Client Name': 'LMN Corporation',
    'Date Sent': '2024-05-25',
    Carrier: 'IJK Express',
    OA: 'OA678',
    Umpire: 'Matthew Clark',
    Address: '678 Elm St, Glentown, USA',
    'Supplement Amt': 90.0,
    Percentage: 12,
    'Date Approved': '2024-06-10',
    Turnaround: 7,
    'Comm Amt': 55.0,
    Notes: 'Detailed report provided to client',
    'Date QB Invoiced': '2024-06-12',
    'Amt TS Paid': 145.0
  },
  {
    'INV #': 'INV013',
    'Completed By': 'Evelyn Turner',
    'Client Name': 'OPQ Enterprises',
    'Date Sent': '2024-05-01',
    Carrier: 'LMN Shipping',
    OA: 'OA901',
    Umpire: 'Ethan Roberts',
    Address: '901 Oak St, Hometown, USA',
    'Supplement Amt': 100.0,
    Percentage: 11,
    'Date Approved': '2024-05-20',
    Turnaround: 6,
    'Comm Amt': 60.0,
    Notes: 'Client satisfaction survey completed',
    'Date QB Invoiced': '2024-05-22',
    'Amt TS Paid': 160.0
  },
  {
    'INV #': 'INV014',
    'Completed By': 'Logan King',
    'Client Name': 'RST Ltd',
    'Date Sent': '2024-05-10',
    Carrier: 'UVW Freight',
    OA: 'OA234',
    Umpire: 'Aria Rivera',
    Address: '234 Cedar St, Rivertown, USA',
    'Supplement Amt': 120.0,
    Percentage: 13,
    'Date Approved': '2024-05-28',
    Turnaround: 7,
    'Comm Amt': 70.0,
    Notes: 'Exceptional service provided',
    'Date QB Invoiced': '2024-05-30',
    'Amt TS Paid': 190.0
  },
  {
    'INV #': 'INV015',
    'Completed By': 'Mia Scott',
    'Client Name': 'WXY Corporation',
    'Date Sent': '2024-05-15',
    Carrier: 'YZA Transport',
    OA: 'OA567',
    Umpire: 'Lucas Gray',
    Address: '567 Walnut St, Newland, USA',
    'Supplement Amt': 80.0,
    Percentage: 10,
    'Date Approved': '2024-06-02',
    Turnaround: 6,
    'Comm Amt': 50.0,
    Notes: 'Timely completion of inspection',
    'Date QB Invoiced': '2024-06-05',
    'Amt TS Paid': 130.0
  }
]

export default data
