export type DataType = {
  id: number
  avatar: string
  fullName: string
  post: string
  email: string
  city: string
  start_date: string
  salary: number
  age: number
  experience: string
  status: number
}

const data: any[] = [
  {
    id: 1,
    inv: 'INV001',
    assigned_to: 'John Doe',
    client_name: 'ABC Corp',
    email: 'a@gmail.com',
    claim_no: '123',
    date_sent: '2024-04-01',
    carrier: 'Michael',
    oa_name: 'OA123',
    oa_email: 'OA123',
    oa_phone_no: 'OA123',
    umpire_name: 'OA123',
    umpire_email: 'OA123',
    umpire_phone_no: 'OA123',
    address: '123 Main St, Anytown, USA',
    city: 'Anytown',
    appraisal_amt: 100,
    percentage: 10,
    date_approved: '2024-04-15',
    inspection_date: '2024-04-15',
    turnaround: 7,
    comm_amt: 50,
    notes: 'Additional inspection required',
    date_qb_invoiced: '2024-04-20',
    date_user_paid: '2024-04-20',
    status: { id: 1, value: 'Open', color: 'success' },
    umpire_status: { id: 1, value: 'None', color: 'default' }
  },
  {
    id: 2,
    inv: 'INV002',
    assigned_to: 'Jane Smith',
    client_name: 'XYZ Inc',
    email: 'b@gmail.com',
    claim_no: '456',
    date_sent: '2024-04-05',
    carrier: 'Jennifer',
    oa_name: 'OA456',
    oa_email: 'OA456',
    oa_phone_no: 'OA456',
    umpire_name: 'OA456',
    umpire_email: 'OA456',
    umpire_phone_no: 'OA456',
    address: '456 Elm St, Othertown, USA',
    city: 'Othertown',
    appraisal_amt: 150,
    percentage: 12,
    date_approved: '2024-04-20',
    inspection_date: '2024-04-20',
    turnaround: 5,
    comm_amt: 60,
    notes: 'No additional notes',
    date_qb_invoiced: '2024-04-25',
    date_user_paid: '2024-04-25',
    status: { id: 2, value: 'Closed', color: 'info' },
    umpire_status: { id: 2, value: 'W9 & Invoice Received', color: 'info' }
  },
  {
    id: 3,
    inv: 'INV003',
    assigned_to: 'Mark Johnson',
    client_name: '123 Company',
    email: 'c@gmail.com',
    claim_no: '789',
    date_sent: '2024-04-10',
    carrier: 'Michael',
    oa_name: 'OA789',
    oa_email: 'OA789',
    oa_phone_no: 'OA789',
    umpire_name: 'OA789',
    umpire_email: 'OA789',
    umpire_phone_no: 'OA789',
    address: '789 Maple Ave, Anycity, USA',
    city: 'Anycity',
    appraisal_amt: 200,
    percentage: 15,
    date_approved: '2024-04-25',
    inspection_date: '2024-04-25',
    turnaround: 6,
    comm_amt: 75,
    notes: 'Pending additional documentation',
    date_qb_invoiced: '2024-04-30',
    date_user_paid: '2024-04-30',
    status: { id: 3, value: 'Open', color: 'success' },
    umpire_status: { id: 3, value: 'None', color: 'default' }
  },
  {
    id: 4,
    inv: 'INV004',
    assigned_to: 'Emily Brown',
    client_name: 'XYZ Corp',
    email: 'd@gmail.com',
    claim_no: '101',
    date_sent: '2024-04-15',
    carrier: 'Jennifer',
    oa_name: 'OA101',
    oa_email: 'OA101',
    oa_phone_no: 'OA101',
    umpire_name: 'OA101',
    umpire_email: 'OA101',
    umpire_phone_no: 'OA101',
    address: '101 Oak Ln, Anothercity, USA',
    city: 'Anothercity',
    appraisal_amt: 120,
    percentage: 8,
    date_approved: '2024-05-01',
    inspection_date: '2024-05-01',
    turnaround: 8,
    comm_amt: 45,
    notes: 'Awaiting client response',
    date_qb_invoiced: '2024-05-05',
    date_user_paid: '2024-05-05',
    status: { id: 4, value: 'Open', color: 'success' },
    umpire_status: { id: 4, value: 'Try To Schedule', color: 'success' }
  },
  {
    id: 5,
    inv: 'INV005',
    assigned_to: 'Sarah Wilson',
    client_name: 'Best Company',
    email: 'e@gmail.com',
    claim_no: '202',
    date_sent: '2024-04-20',
    carrier: 'Emily',
    oa_name: 'OA202',
    oa_email: 'OA202',
    oa_phone_no: 'OA202',
    umpire_name: 'OA202',
    umpire_email: 'OA202',
    umpire_phone_no: 'OA202',
    address: '202 Pine St, Newcity, USA',
    city: 'Newcity',
    appraisal_amt: 180,
    percentage: 10,
    date_approved: '2024-05-05',
    inspection_date: '2024-05-05',
    turnaround: 5,
    comm_amt: 70,
    notes: 'Client confirmed details',
    date_qb_invoiced: '2024-05-10',
    date_user_paid: '2024-05-10',
    status: { id: 5, value: 'Closed', color: 'info' },
    umpire_status: { id: 5, value: 'Inspection Schedule', color: 'info' }
  },
  {
    id: 6,
    inv: 'INV006',
    assigned_to: 'Michael Davis',
    client_name: 'Great Corporation',
    email: 'f@gmail.com',
    claim_no: '303',
    date_sent: '2024-04-25',
    carrier: 'Ashley',
    oa_name: 'OA303',
    oa_email: 'OA303',
    oa_phone_no: 'OA303',
    umpire_name: 'OA303',
    umpire_email: 'OA303',
    umpire_phone_no: 'OA303',
    address: '303 Cedar St, Yetanothercity, USA',
    city: 'Yetanothercity',
    appraisal_amt: 250,
    percentage: 12,
    date_approved: '2024-05-10',
    inspection_date: '2024-05-10',
    turnaround: 6,
    comm_amt: 80,
    notes: 'Pending final review',
    date_qb_invoiced: '2024-05-15',
    date_user_paid: '2024-05-15',
    status: { id: 6, value: 'Open', color: 'success' },
    umpire_status: { id: 6, value: 'None', color: 'default' }
  },
  {
    id: 7,
    inv: 'INV007',
    assigned_to: 'Alex Johnson',
    client_name: 'Superior Industries',
    email: 'g@gmail.com',
    claim_no: '404',
    date_sent: '2024-04-30',
    carrier: 'Robert',
    oa_name: 'OA404',
    oa_email: 'OA404',
    oa_phone_no: 'OA404',
    umpire_name: 'OA404',
    umpire_email: 'OA404',
    umpire_phone_no: 'OA404',
    address: '404 Walnut St, Metropolitan City, USA',
    city: 'Metropolitan City',
    appraisal_amt: 300,
    percentage: 15,
    date_approved: '2024-05-15',
    inspection_date: '2024-05-15',
    turnaround: 7,
    comm_amt: 90,
    notes: 'Ready for final approval',
    date_qb_invoiced: '2024-05-20',
    date_user_paid: '2024-05-20',
    status: { id: 7, value: 'Open', color: 'success' },
    umpire_status: { id: 7, value: 'Roof Denied', color: 'success' }
  },
  {
    id: 8,
    inv: 'INV008',
    assigned_to: 'Emma Garcia',
    client_name: 'Top Organization',
    email: 'h@gmail.com',
    claim_no: '505',
    date_sent: '2024-05-05',
    carrier: 'William',
    oa_name: 'OA505',
    oa_email: 'OA505',
    oa_phone_no: 'OA505',
    umpire_name: 'OA505',
    umpire_email: 'OA505',
    umpire_phone_no: 'OA505',
    address: '505 Chestnut St, Capital City, USA',
    city: 'Capital City',
    appraisal_amt: 220,
    percentage: 10,
    date_approved: '2024-05-20',
    inspection_date: '2024-05-20',
    turnaround: 6,
    comm_amt: 75,
    notes: 'Awaiting client confirmation',
    date_qb_invoiced: '2024-05-25',
    date_user_paid: '2024-05-25',
    status: { id: 8, value: 'Open', color: 'success' },
    umpire_status: { id: 8, value: 'Inspection Schedule', color: 'success' }
  },
  {
    id: 9,
    inv: 'INV005',
    assigned_to: 'Sarah Wilson',
    client_name: 'Best Company',
    email: 'e@gmail.com',
    claim_no: '202',
    date_sent: '2024-04-20',
    carrier: 'Melissa',
    oa_name: 'OA202',
    oa_email: 'OA202',
    oa_phone_no: 'OA202',
    umpire_name: 'OA202',
    umpire_email: 'OA202',
    umpire_phone_no: 'OA202',
    address: '202 Pine St, Newcity, USA',
    city: 'Newcity',
    appraisal_amt: 180,
    percentage: 10,
    date_approved: '2024-05-05',
    inspection_date: '2024-05-05',
    turnaround: 5,
    comm_amt: 70,
    notes: 'Client confirmed details',
    date_qb_invoiced: '2024-05-10',
    date_user_paid: '2024-05-10',
    status: { id: 9, value: 'Closed', color: 'info' },
    umpire_status: { id: 9, value: 'None', color: 'default' }
  },
  {
    id: 10,
    inv: 'INV006',
    assigned_to: 'Michael Davis',
    client_name: 'Great Corporation',
    email: 'f@gmail.com',
    claim_no: '303',
    date_sent: '2024-04-25',
    carrier: 'Melissa',
    oa_name: 'OA303',
    oa_email: 'OA303',
    oa_phone_no: 'OA303',
    umpire_name: 'OA303',
    umpire_email: 'OA303',
    umpire_phone_no: 'OA303',
    address: '303 Cedar St, Yetanothercity, USA',
    city: 'Yetanothercity',
    appraisal_amt: 250,
    percentage: 12,
    date_approved: '2024-05-10',
    inspection_date: '2024-05-10',
    turnaround: 6,
    comm_amt: 80,
    notes: 'Pending final review',
    date_qb_invoiced: '2024-05-15',
    date_user_paid: '2024-05-15',
    status: { id: 10, value: 'Open', color: 'success' },
    umpire_status: { id: 10, value: 'Payment Sent', color: 'success' }
  },
  {
    id: 11,
    inv: 'INV007',
    assigned_to: 'Alex Johnson',
    client_name: 'Superior Industries',
    email: 'g@gmail.com',
    claim_no: '404',
    date_sent: '2024-04-30',
    carrier: 'MNO Shipping',
    oa_name: 'OA404',
    oa_email: 'OA404',
    oa_phone_no: 'OA404',
    umpire_name: 'OA404',
    umpire_email: 'OA404',
    umpire_phone_no: 'OA404',
    address: '404 Walnut St, Metropolitan City, USA',
    city: 'Metropolitan City',
    appraisal_amt: 300,
    percentage: 15,
    date_approved: '2024-05-15',
    inspection_date: '2024-05-15',
    turnaround: 7,
    comm_amt: 90,
    notes: 'Ready for final approval',
    date_qb_invoiced: '2024-05-20',
    date_user_paid: '2024-05-20',
    status: { id: 11, value: 'Open', color: 'success' },
    umpire_status: { id: 11, value: 'Try To Schedule', color: 'success' }
  },
  {
    id: 12,
    inv: 'INV0012',
    assigned_to: 'Emma Garcia',
    client_name: 'Top Organization',
    email: 'h@gmail.com',
    claim_no: '505',
    date_sent: '2024-05-05',
    carrier: 'PQR Shipping',
    oa_name: 'OA505',
    oa_email: 'OA505',
    oa_phone_no: 'OA505',
    umpire_name: 'OA505',
    umpire_email: 'OA505',
    umpire_phone_no: 'OA505',
    address: '505 Chestnut St, Capital City, USA',
    city: 'Capital City',
    appraisal_amt: 220,
    percentage: 10,
    date_approved: '2024-05-20',
    inspection_date: '2024-05-20',
    turnaround: 6,
    comm_amt: 75,
    notes: 'Asad client confirmation',
    date_qb_invoiced: '2024-05-25',
    date_user_paid: '2024-05-25',
    status: { id: 12, value: 'Scheduling Inspection', color: 'default' },
    umpire_status: { id: 12, value: 'Inspection Schedule', color: 'default' }
  }
]

export default data
